name: Python tests

on:
  push:
    branches: [ main, "feature/*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  MATURIN_VERSION: '1.5.1'
  RUST_TOOLCHAIN: nightly-2024-05-14

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install "maturin[patchelf]"==${{ env.MATURIN_VERSION }}
        pip install -r tests/requirements.txt
      working-directory: ./py_maplib

    - name: Set up nightly rust
      run: |
        rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
        rustup default ${{ env.RUST_TOOLCHAIN }}

    - name: Build install package
      run: |
        source .venv/bin/activate
        maturin develop
      working-directory: ./py_maplib

    - name: pytest
      run: |
        source ../.venv/bin/activate
        pytest
      working-directory: ./py_maplib/tests
