name: Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_TOOLCHAIN: nightly-2025-05-21

jobs:
  build_and_test:
    runs-on:
      group: ubuntu_runners

    steps:
    - uses: actions/checkout@v4

    - name: Upgrade rust with nightly
      run: |
        rustup update
        rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
        rustup default ${{ env.RUST_TOOLCHAIN }}

    - name: Build
      run: cargo build --verbose --all
    - name: Run rust tests
      run: cargo test --verbose --all
